//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aftermarket_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsMaster
    {
        public Nullable<short> PartManufacturerId { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public Nullable<int> PartTypeId { get; set; }
        public string PartDescription { get; set; }
        public int PartMasterId { get; set; }
    
        public virtual PartsManufacturer PartsManufacturer { get; set; }
        public virtual PartsType PartsType { get; set; }
    }
}
