//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aftermarket_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsVehicleXReference
    {
        public int WasModelId { get; set; }
        public int PartsMasterId { get; set; }
        public Nullable<int> ShimId { get; set; }
        public int PartsVehicleXRefId { get; set; }
    }
}
