//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aftermarket_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsVehicleMaster
    {
        public string PartNumber { get; set; }
        public string VehicleManufacturer { get; set; }
        public string VehicleModelName { get; set; }
        public string VehicleDescription { get; set; }
        public Nullable<int> VehicleYearFrom { get; set; }
        public Nullable<int> VehicleYearTo { get; set; }
        public int PartVehicleMasterId { get; set; }
    }
}
